services:
  web:
    image: php:8.2-apache
    container_name: quizpengupil_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    command: >
      bash -c "
      docker-php-ext-install mysqli &&
      apache2-foreground
      "

  db:
    image: mysql:8.0
    container_name: quizpengupil_db
    environment:
      MYSQL_DATABASE: quizpengupil
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
